### ISSUE TITLE
Mailwurst struggles using npm 2.7.4 - aka OMG I am f*cked

### ISSUE THREAD

**Issue by luebbert42** [m0ppers/mailwurst#3]
mailwurst --relayserver=smtprelaypool.ispgateway.de --rewriteto=test@example.com --user=test@example.com --password --port=9025
Password:
 ∙• Mailwurst ready at port 9025 ... /usr/local/lib/node_modules/mailwurst/node_modules/simplesmtp/lib/client.js:907
    this._xoauth2.reconnectCount = 0;
                                 ^
TypeError: Cannot assign to read only property 'reconnectCount' of false
    at SMTPClient._actionAUTHComplete (/usr/local/lib/node_modules/mailwurst/node_modules/simplesmtp/lib/client.js:907:34)
    at SMTPClient._onData (/usr/local/lib/node_modules/mailwurst/node_modules/simplesmtp/lib/client.js:348:29)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by luebbert42** [comment]
updated to node 0.12.7 -> same result

**Comment by luebbert42** [comment]
ok, seems to be something happening since node 0.12

I hacked client.js mentioned above and it works again now for me:

if(this._xoauth2){
    this._xoauth2.reconnectCount = 0;
}

**Comment by luebbert42** [comment]
Did I mention that I love talking to myself.

**Comment by luebbert42** [comment]
I really do.

**Comment by m0ppers** [comment]
I love listening to you talking to yourself!

**Comment by m0ppers** [comment]
According to this http://stackoverflow.com/questions/28579806/heroku-issue-with-nodemailer the issue might be solvable by just upgrading nodemailer :O would you mind making a pull request? Lots or open source props and karma will shine upon you :D

**Comment by m0ppers** [comment]
not to mention being well positioned in the market as a javascript developer :O

**Comment by luebbert42** [comment]
super awesome senior success javascript developer enterprise edition.

**Comment by luebbert42** [comment]
#4
